import type { Metadata } from 'next';
import { IBM_Plex_Mono, Inter, Monoton, Poppins } from 'next/font/google';
import './globals.css';
import HeaderPage from './components/header/header';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});
const monoton = Monoton({
  variable: '--font-monoton',
  subsets: ['latin'],
  weight: ['400'],
});

const plexMono = IBM_Plex_Mono({
  variable: '--font-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500'],
});
const poppins = Poppins({
  variable: '--font-plex-poppins',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${inter.variable} ${plexMono.variable} ${monoton.variable} ${poppins.variable}`}
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
